import Head from "next/head";
import Image from "next/image";
import Indexmain1 from "../components/index_page/Indexmain1";
import Kategori from "../components/Kategori";
import List from "../components/List";
import Brands from "../components/Brands";
import {MongoClient} from "mongodb";

export async function getServerSideProps(context){
	const req= context.req;
	const res = context.res; // incoming request things
  const uri ="MONGO_DB_ADRESS";
  const client = new MongoClient(uri, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });
  
  try{
    await client.connect();
    const database = client.db("alisveris_db");
    const movies = database.collection("urunler");
    const finder=await movies.find({stock:10}).toArray().then(docs =>docs)
  
    console.log(finder)
    if(finder){
      
      await client.close();
      return{
        props:{
        urun:JSON.stringify(finder) 
        }
        }
      
    }
    else{
      console.log("not found")
    }
  }
  catch(err){
    console.log(err.toString())
  }

    
  }


export default function Home(props) {





  return (
    <div className="main">
      <Head>
        <title>Eticaret</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Indexmain1 />
      <Kategori />

      <List urun={JSON.parse(props.urun)}/>
      <Brands />
    </div>
  );
}
